### ISSUE TITLE
UAInspector database refuses to download

### ISSUE THREAD

**Issue by pmarreck** [elixytics/ua_inspector#27]
This issue cropped up just today, I (unfortunately) have my stack dynamically downloading the DB at app launch, but now my app is dead because it turns out the DB's won't download currently for some reason (possibly a cert issue?), I should have switched my app config over to keeping the DB in my repo, but it's too late to do that now sigh

**Comment by mneudert** [comment]
If there is a cert issue it usually helps to update your `:hackney` version using `mix deps.update hackney`. If that does not help please try running `mix ua_inspector.download` to check if a somewhat helpful error message is produced.

**Comment by pmarreck** [comment]
Thanks for the tips!

**Comment by nallwhy** [comment]
I'm getting this message too often recently.

```
This command will replace any existing files!
** (MatchError) no match of right hand side value: {:error, :timeout}
    (ua_inspector 2.2.0) lib/ua_inspector/downloader.ex:89: UAInspector.Downloader.download_file/2
    (ua_inspector 2.2.0) lib/ua_inspector/downloader.ex:63: anonymous fn/1 in UAInspector.Downloader.download/1
    (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (ua_inspector 2.2.0) lib/mix/tasks/ua_inspector/download.ex:65: Mix.Tasks.UaInspector.Download.perform_download/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.3) lib/mix/task.ex:452: Mix.Task.run_alias/5
    (mix 1.12.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
** (exit) 1
    (mix 1.12.3) lib/mix/tasks/cmd.ex:64: Mix.Tasks.Cmd.run/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.3) lib/mix/project.ex:353: Mix.Project.in_project/4
    (elixir 1.12.3) lib/file.ex:1560: File.cd!/2
    (mix 1.12.3) lib/mix/task.ex:520: anonymous fn/4 in Mix.Task.recur/1
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.12.3) lib/mix/task.ex:519: Mix.Task.recur/1
    (mix 1.12.3) lib/mix/project_stack.ex:181: Mix.ProjectStack.recur/1
```

**Comment by mneudert** [comment]
You could try increasing the `:recv_timeout` in your configuration:

```elixir
# :hackney default is 5_000
config :ua_inspector,
  http_opts: [recv_timeout: 10_000]
```

Everything configured in `:http_opts` will be passed directly to `:hackney.request/5`.

_As release `v2.2.0` is pinned to a specific database that will not change you could also cache the database indefinitely until there is a newer release with a newer database._

**Comment by ukutaht** [comment]
@mneudert Can I ask what affiliation do you have, or what motivates you to work on these libraries?

We use _ref_inspector_, _ua_inspector_ and _geolix_ for [Plausible Analytics](https://github.com/plausible/analytics). It's in our interest to keep these dependencies up to date as much as possible. We would be happy to provide some sponsorship funding in order to  support the development. What do you think?

**Comment by mneudert** [comment]
Hey @ukutaht,

I am developing all those libraries to have something to use myself. With the sometimes showing side effect of me just using the code from source and not releasing a new version because of "works for me".

Could you:

- open a bunch of issues everywhere with the immediate issues you would like to get resolved (even just things like "please release")
- drop me a mail (address is found in just about every commit or on my hex profile) or open a separate issue with some way to reach you for a chat? (slack, discord, skype, mail, ...)

As I am trying to get back into actually releasing stuff instead of just silently using it I think we should get something going :)
