### ISSUE TITLE
Upgrade to 3.0 throwing error on download

### ISSUE THREAD

**Issue by coladarci** [elixytics/ua_inspector#28]
Please advise; not sure if this is temporary or a real bug.. thanks!
```
iex> UAInspector.Downloader.download()
** (MatchError) no match of right hand side value: {:error, {:status, 404, "https://raw.githubusercontent.com/matomo-org/device-detector/3.13.1/regexes/device/shell_tv.yml"}}
    (ua_inspector 3.0.1) lib/ua_inspector/downloader.ex:89: UAInspector.Downloader.download_file/2
    (ua_inspector 3.0.1) lib/ua_inspector/downloader.ex:63: anonymous fn/1 in UAInspector.Downloader.download/1
    (elixir 1.13.2) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (ua_inspector 3.0.1) lib/ua_inspector/downloader.ex:47: UAInspector.Downloader.download/0
```

**Comment by mneudert** [comment]
I would guess you have configured a `:remote_release` (`3.13.1` to be specific) that is now no longer usable.

By now the library is providing a proper default release version that is verified to be working instead of a moving branch. If you remove your configuration everything should again work as expected.

_The error message should probably be changed to reflect that :thinking:_

**Comment by coladarci** [comment]
Ah - I forgot about doing this (https://github.com/elixir-inspector/ua_inspector/issues/23) thank you!
